// Mock product data for Fresh Market

export const mockProducts = {
    vegetables: [
        {
            id: 1,
            name: 'Xà Lách Tươi (300 gram)',
            category: 'vegetables',
            subcategory: 'leafy',
            price: 28000,
            originalPrice: 35000,
            discount: 19,
            rating: 5,
            reviewCount: 28,
            soldCount: 345,
            image: 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=400&q=80',
            isOrganic: true,
            inStock: true,
        },
        {
            id: 2,
            name: 'Cải Bó Xôi Baby (200 gram)',
            category: 'vegetables',
            subcategory: 'leafy',
            price: 22000,
            originalPrice: null,
            discount: 0,
            rating: 5,
            reviewCount: 45,
            soldCount: 567,
            image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&q=80',
            isOrganic: true,
            inStock: true,
        },
        {
            id: 3,
            name: 'Cà Chua Bi (500 gram)',
            category: 'vegetables',
            subcategory: 'fruit-veg',
            price: 42000,
            originalPrice: 48000,
            discount: 12,
            rating: 5,
            reviewCount: 89,
            soldCount: 723,
            image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400&q=80',
            isOrganic: false,
            inStock: true,
        },
        {
            id: 4,
            name: 'Ớt Chuông Đỏ (300 gram)',
            category: 'vegetables',
            subcategory: 'fruit-veg',
            price: 48000,
            originalPrice: null,
            discount: 0,
            rating: 4,
            reviewCount: 34,
            soldCount: 234,
            image: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400&q=80',
            isOrganic: false,
            inStock: true,
        },
        {
            id: 5,
            name: 'Bơ (500 gram)',
            category: 'vegetables',
            subcategory: 'fruit-veg',
            price: 80000,
            originalPrice: 99000,
            discount: 19,
            rating: 5,
            reviewCount: 156,
            soldCount: 891,
            image: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&q=80',
            isOrganic: true,
            inStock: true,
        },
        {
            id: 6,
            name: 'Nấm Portobello (300 gram)',
            category: 'vegetables',
            subcategory: 'mushroom',
            price: 58000,
            originalPrice: null,
            discount: 0,
            rating: 5,
            reviewCount: 67,
            soldCount: 456,
            image: 'https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=400&q=80',
            isOrganic: false,
            inStock: true,
        },
        {
            id: 7,
            name: 'Súp Lơ Xanh (400 gram)',
            category: 'vegetables',
            subcategory: 'cruciferous',
            price: 35000,
            originalPrice: null,
            discount: 0,
            rating: 4,
            reviewCount: 23,
            soldCount: 178,
            image: 'https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=400&q=80',
            isOrganic: true,
            inStock: true,
        },
        {
            id: 8,
            name: 'Cà Rót Baby (500 gram)',
            category: 'vegetables',
            subcategory: 'root',
            price: 32000,
            originalPrice: 40000,
            discount: 20,
            rating: 5,
            reviewCount: 91,
            soldCount: 612,
            image: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400&q=80',
            isOrganic: true,
            inStock: true,
        },
    ],

    fruits: [
        {
            id: 101,
            name: 'Thanh Long Ruột Đỏ (1 kilogram)',
            category: 'fruits',
            subcategory: 'vietnam',
            price: 45000,
            originalPrice: null,
            discount: 0,
            rating: 5,
            reviewCount: 48,
            soldCount: 567,
            image: 'https://images.unsplash.com/photo-1526318472351-c75fcf070305?w=400&q=80',
            isOrganic: false,
            inStock: true,
        },
        {
            id: 102,
            name: 'Cherry Đỏ (500 gram)',
            category: 'fruits',
            subcategory: 'imported',
            price: 180000,
            originalPrice: null,
            discount: 0,
            rating: 5,
            reviewCount: 73,
            soldCount: 845,
            image: 'https://images.unsplash.com/photo-1528821128474-27f963b062bf?w=400&q=80',
            isOrganic: false,
            inStock: true,
        },
        {
            id: 103,
            name: 'Nhãn Lồng (1 kilogram)',
            category: 'fruits',
            subcategory: 'vietnam',
            price: 65000,
            originalPrice: 85000,
            discount: 24,
            rating: 5,
            reviewCount: 59,
            soldCount: 612,
            image: 'https://images.unsplash.com/photo-1577234286642-fc512a5f8f11?w=400&q=80',
            isOrganic: true,
            inStock: true,
        },
        {
            id: 104,
            name: 'Dâu Tây Đà Lạt (250 gram)',
            category: 'fruits',
            subcategory: 'vietnam',
            price: 95000,
            originalPrice: null,
            discount: 0,
            rating: 5,
            reviewCount: 128,
            soldCount: 923,
            image: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400&q=80',
            isOrganic: true,
            inStock: true,
        },
        {
            id: 105,
            name: 'Cam Sành (1 kilogram)',
            category: 'fruits',
            subcategory: 'vietnam',
            price: 38000,
            originalPrice: null,
            discount: 0,
            rating: 4,
            reviewCount: 67,
            soldCount: 734,
            image: 'https://images.unsplash.com/photo-1547514701-42782101795e?w=400&q=80',
            isOrganic: false,
            inStock: true,
        },
        {
            id: 106,
            name: 'Táo Envy New Zealand (500 gram)',
            category: 'fruits',
            subcategory: 'imported',
            price: 120000,
            originalPrice: null,
            discount: 0,
            rating: 5,
            reviewCount: 92,
            soldCount: 456,
            image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400&q=80',
            isOrganic: false,
            inStock: true,
        },
        {
            id: 107,
            name: 'Xoài Cát Hòa Lộc (1 kilogram)',
            category: 'fruits',
            subcategory: 'vietnam',
            price: 75000,
            originalPrice: null,
            discount: 0,
            rating: 5,
            reviewCount: 145,
            soldCount: 1023,
            image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=400&q=80',
            isOrganic: true,
            inStock: true,
        },
        {
            id: 108,
            name: 'Nho Xanh Không Hạt (500 gram)',
            category: 'fruits',
            subcategory: 'imported',
            price: 145000,
            originalPrice: null,
            discount: 0,
            rating: 5,
            reviewCount: 88,
            soldCount: 567,
            image: 'https://images.unsplash.com/photo-1599819177626-c2f9c92a1c0b?w=400&q=80',
            isOrganic: false,
            inStock: true,
        },
    ],
}

export const categories = {
    vegetables: {
        id: 'vegetables',
        name: 'Rau, Củ & Nấm',
        tabs: ['Tất cả', 'Rau Ăn Lá', 'Củ, Quả', 'Nấm, Đậu Hũ'],
    },
    fruits: {
        id: 'fruits',
        name: 'Trái Cây Tươi Ngon',
        tabs: ['Tất cả', 'Trái Việt Nam', 'Trái Nhập Khẩu'],
    },
    meatSeafood: {
        id: 'meatSeafood',
        name: 'Thịt, Cá, Trứng & Hải Sản',
        tabs: ['Tất cả', 'Hải Sản', 'Thịt Heo', 'Thịt Bò', 'Thịt Gà, Vịt & Chim'],
    },
    driedFood: {
        id: 'driedFood',
        name: 'Thực Phẩm Khô',
        tabs: ['Tất cả', 'Trái Cây Sấy', 'Khô Chế Biến Sẵn'],
    },
}

// Add meat and seafood products
mockProducts.meatSeafood = [
    {
        id: 201,
        name: 'Khay Tôm Sú (500 gram)',
        category: 'meatSeafood',
        subcategory: 'seafood',
        price: 320000,
        originalPrice: 385000,
        discount: 17,
        rating: 5,
        reviewCount: 89,
        soldCount: 456,
        image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=400&q=80',
        isOrganic: false,
        inStock: true,
    },
    {
        id: 202,
        name: 'Khay Thịt Ba Chỉ Heo (500 gram)',
        category: 'meatSeafood',
        subcategory: 'pork',
        price: 145000,
        originalPrice: null,
        discount: 0,
        rating: 5,
        reviewCount: 102,
        soldCount: 678,
        image: 'https://images.unsplash.com/photo-1602470520998-f4a52199a3d6?w=400&q=80',
        isOrganic: false,
        inStock: true,
    },
    {
        id: 203,
        name: 'Khay Thịt Bò Nạm (500 gram)',
        category: 'meatSeafood',
        subcategory: 'beef',
        price: 185000,
        originalPrice: null,
        discount: 0,
        rating: 5,
        reviewCount: 103,
        soldCount: 523,
        image: 'https://images.unsplash.com/photo-1603048588665-791ca8aea617?w=400&q=80',
        isOrganic: false,
        inStock: true,
    },
    {
        id: 204,
        name: 'Khay Nghêu Tươi (500 gram)',
        category: 'meatSeafood',
        subcategory: 'seafood',
        price: 95000,
        originalPrice: null,
        discount: 0,
        rating: 4,
        reviewCount: 42,
        soldCount: 234,
        image: 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?w=400&q=80',
        isOrganic: false,
        inStock: true,
    },
    {
        id: 205,
        name: 'Cá Hồi Phi Lê (300 gram)',
        category: 'meatSeafood',
        subcategory: 'seafood',
        price: 285000,
        originalPrice: null,
        discount: 0,
        rating: 5,
        reviewCount: 156,
        soldCount: 789,
        image: 'https://images.unsplash.com/photo-1574781330855-d0db8cc6a79c?w=400&q=80',
        isOrganic: false,
        inStock: true,
    },
    {
        id: 206,
        name: 'Ức Gà Phi Lê (500 gram)',
        category: 'meatSeafood',
        subcategory: 'chicken',
        price: 125000,
        originalPrice: null,
        discount: 0,
        rating: 5,
        reviewCount: 98,
        soldCount: 612,
        image: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400&q=80',
        isOrganic: false,
        inStock: true,
    },
    {
        id: 207,
        name: 'Mực Ống Tươi (500 gram)',
        category: 'meatSeafood',
        subcategory: 'seafood',
        price: 165000,
        originalPrice: null,
        discount: 0,
        rating: 5,
        reviewCount: 73,
        soldCount: 445,
        image: 'https://images.unsplash.com/photo-1599084993091-1cb5c0721cc6?w=400&q=80',
        isOrganic: false,
        inStock: true,
    },
    {
        id: 208,
        name: 'Thịt Nạc Vai Heo (500 gram)',
        category: 'meatSeafood',
        subcategory: 'pork',
        price: 135000,
        originalPrice: null,
        discount: 0,
        rating: 5,
        reviewCount: 87,
        soldCount: 567,
        image: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=400&q=80',
        isOrganic: false,
        inStock: true,
    },
]

// Add dried food products
mockProducts.driedFood = [
    {
        id: 301,
        name: 'Xoài Sấy (200 gram)',
        category: 'driedFood',
        subcategory: 'dried-fruit',
        price: 65000,
        originalPrice: null,
        discount: 0,
        rating: 5,
        reviewCount: 87,
        soldCount: 923,
        image: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=400&q=80',
        isOrganic: true,
        inStock: true,
    },
    {
        id: 302,
        name: 'Mực Khô (250 gram)',
        category: 'driedFood',
        subcategory: 'processed',
        price: 185000,
        originalPrice: null,
        discount: 0,
        rating: 5,
        reviewCount: 102,
        soldCount: 1234,
        image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400&q=80',
        isOrganic: false,
        inStock: true,
    },
    {
        id: 303,
        name: 'Chuối Sấy (150 gram)',
        category: 'driedFood',
        subcategory: 'dried-fruit',
        price: 45000,
        originalPrice: 55000,
        discount: 18,
        rating: 5,
        reviewCount: 174,
        soldCount: 1456,
        image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400&q=80',
        isOrganic: true,
        inStock: true,
    },
    {
        id: 304,
        name: 'Tôm Khô (200 gram)',
        category: 'driedFood',
        subcategory: 'processed',
        price: 195000,
        originalPrice: 225000,
        discount: 13,
        rating: 5,
        reviewCount: 98,
        soldCount: 1123,
        image: 'https://images.unsplash.com/photo-1599084993091-1cb5c0721cc6?w=400&q=80',
        isOrganic: false,
        inStock: true,
    },
    {
        id: 305,
        name: 'Dứa Sấy (200 gram)',
        category: 'driedFood',
        subcategory: 'dried-fruit',
        price: 55000,
        originalPrice: null,
        discount: 0,
        rating: 5,
        reviewCount: 145,
        soldCount: 876,
        image: 'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=400&q=80',
        isOrganic: true,
        inStock: true,
    },
    {
        id: 306,
        name: 'Nho Khô (150 gram)',
        category: 'driedFood',
        subcategory: 'dried-fruit',
        price: 75000,
        originalPrice: null,
        discount: 0,
        rating: 5,
        reviewCount: 123,
        soldCount: 734,
        image: 'https://images.unsplash.com/photo-1587411768941-1c0d0b9e5d2f?w=400&q=80',
        isOrganic: false,
        inStock: true,
    },
    {
        id: 307,
        name: 'Khô Bò Miếng (100 gram)',
        category: 'driedFood',
        subcategory: 'processed',
        price: 125000,
        originalPrice: null,
        discount: 0,
        rating: 5,
        reviewCount: 167,
        soldCount: 945,
        image: 'https://images.unsplash.com/photo-1588347818036-8fc5ec0c5e1a?w=400&q=80',
        isOrganic: false,
        inStock: true,
    },
    {
        id: 308,
        name: 'Mít Sấy (200 gram)',
        category: 'driedFood',
        subcategory: 'dried-fruit',
        price: 85000,
        originalPrice: null,
        discount: 0,
        rating: 5,
        reviewCount: 92,
        soldCount: 567,
        image: 'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=400&q=80',
        isOrganic: true,
        inStock: true,
    },
]
